version: "3.7"

services:
  api:
    container_name: api
    build: ../api
    hostname: api
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ../api:/usr/src/app/api
    working_dir: /usr/src/app/api
    command: 'npm start'

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ../docker/mysql-data:/var/lib/mysql
      - ../docker/mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: placesapp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000